<?php

$rules = [
    'array_syntax'                                  => ['syntax' => 'short'],
    'binary_operator_spaces'                        => ['default' => 'single_space', 'operators' => ['=' => 'align_single_space', '=>' => 'align_single_space', '+=' => 'align_single_space', '*=' => 'align_single_space', '/=' => 'align_single_space', '-=' => 'align_single_space']],
    'blank_line_after_namespace'                    => TRUE,
    'blank_line_after_opening_tag'                  => TRUE,
    'blank_line_before_statement'                   => ['statements' => ['return', 'break', 'throw', 'try', 'if']],
    'braces'                                        => ['allow_single_line_closure' => TRUE, 'position_after_functions_and_oop_constructs' => 'same'],
    'cast_spaces'                                   => TRUE,
    'class_attributes_separation'                   => ['elements' => ['method']],
    'class_definition'                              => TRUE,
    'concat_space'                                  => ['spacing' => 'none'],
    'no_unneeded_curly_braces'                      => TRUE,
    'not_operator_with_space'                       => FALSE,
    'combine_consecutive_issets'                    => TRUE,
    'not_operator_with_successor_space'             => FALSE,
    'declare_equal_normalize'                       => TRUE,
    'elseif'                                        => TRUE,
    'compact_nullable_typehint'                     => TRUE,
    'encoding'                                      => TRUE,
    'full_opening_tag'                              => TRUE,
    'constant_case'                                 => ['case' => 'upper'],
    'fully_qualified_strict_types'                  => FALSE,
    'function_declaration'                          => TRUE,
    'function_typehint_space'                       => TRUE,
    'heredoc_to_nowdoc'                             => TRUE,
    'global_namespace_import'                       => ['import_classes' => TRUE, 'import_constants' => TRUE],
    'include'                                       => TRUE,
    'increment_style'                               => ['style' => 'post'],
    'indentation_type'                              => TRUE,
    'linebreak_after_opening_tag'                   => TRUE,
    'line_ending'                                   => TRUE,
    'lowercase_cast'                                => TRUE,
    'new_with_braces'                               => TRUE,
    'lowercase_keywords'                            => TRUE,
    'lowercase_static_reference'                    => TRUE,
    'magic_method_casing'                           => TRUE,
    'magic_constant_casing'                         => TRUE,
    'method_argument_space'                         => TRUE,
    'native_function_casing'                        => TRUE,
    'no_alias_functions'                            => TRUE,
    'no_extra_blank_lines'                          => ['tokens' => ['throw', 'use', 'use_trait']],
    'no_blank_lines_after_class_opening'            => FALSE,
    'no_empty_comment'                              => TRUE,
    'no_closing_tag'                                => TRUE,
    'explicit_string_variable'                      => TRUE,
    'explicit_indirect_variable'                    => TRUE,
    'no_empty_phpdoc'                               => TRUE,
    'no_short_echo_tag'                             => FALSE,
    'no_empty_statement'                            => TRUE,
    'phpdoc_to_return_type'                         => TRUE,
    'no_leading_import_slash'                       => TRUE,
    'no_leading_namespace_whitespace'               => TRUE,
    'no_mixed_echo_print'                           => ['use' => 'echo'],
    'no_multiline_whitespace_around_double_arrow'   => TRUE,
    'multiline_whitespace_before_semicolons'        => ['strategy' => 'no_multi_line'],
    'no_short_bool_cast'                            => TRUE,
    'no_singleline_whitespace_before_semicolons'    => TRUE,
    'no_spaces_after_function_name'                 => TRUE,
    'no_spaces_around_offset'                       => TRUE,
    'no_unused_imports'                             => TRUE,
    'no_spaces_inside_parenthesis'                  => TRUE,
    'no_trailing_comma_in_list_call'                => TRUE,
    'no_trailing_comma_in_singleline_array'         => TRUE,
    'no_trailing_whitespace'                        => TRUE,
    'no_trailing_whitespace_in_comment'             => TRUE,
    'no_unneeded_control_parentheses'               => TRUE,
    'no_unreachable_default_argument_value'         => TRUE,
    'no_useless_return'                             => TRUE,
    'no_whitespace_before_comma_in_array'           => TRUE,
    'phpdoc_separation'                             => TRUE,
    'single_line_throw'                             => TRUE,
    'no_whitespace_in_blank_line'                   => TRUE,
    'normalize_index_brace'                         => TRUE,
    'object_operator_without_whitespace'            => TRUE,
    'ordered_imports'                               => ['sortAlgorithm' => 'length'],
    'phpdoc_inline_tag'                             => TRUE,
    'phpdoc_no_access'                              => TRUE,
    'phpdoc_no_package'                             => TRUE,
    'phpdoc_no_useless_inheritdoc'                  => TRUE,
    'phpdoc_scalar'                                 => TRUE,
    'phpdoc_order'                                  => TRUE,
    'phpdoc_single_line_var_spacing'                => TRUE,
    'phpdoc_to_param_type'                          => FALSE,
    'phpdoc_var_annotation_correct_order'           => TRUE,
    'phpdoc_summary'                                => TRUE,
    'phpdoc_trim'                                   => TRUE,
    'phpdoc_types'                                  => TRUE,
    'phpdoc_var_without_name'                       => TRUE,
    'psr4'                                          => TRUE,
    'self_accessor'                                 => TRUE,
    'short_scalar_cast'                             => TRUE,
    'phpdoc_no_empty_return'                        => TRUE,
    'simplified_null_return'                        => FALSE,
    'phpdoc_trim_consecutive_blank_line_separation' => TRUE,
    'single_blank_line_at_eof'                      => TRUE,
    'single_blank_line_before_namespace'            => TRUE,
    'method_chaining_indentation'                   => TRUE,
    'heredoc_indentation'                           => TRUE,
    'single_class_element_per_statement'            => TRUE,
    'phpdoc_indent'                                 => TRUE,
    'single_import_per_statement'                   => TRUE,
    'single_line_after_imports'                     => TRUE,
    'phpdoc_align'                                  => ['align' => 'vertical', 'tags' => ['param', 'property', 'property-read', 'property-write', 'return', 'throws', 'type', 'var', 'method']],
    'single_quote'                                  => TRUE,
    'space_after_semicolon'                         => FALSE,
    'standardize_not_equals'                        => TRUE,
    'switch_case_semicolon_to_colon'                => TRUE,
    'switch_case_space'                             => TRUE,
    'ternary_operator_spaces'                       => TRUE,
    'trailing_comma_in_multiline_array'             => TRUE,
    'trim_array_spaces'                             => TRUE,
    'unary_operator_spaces'                         => TRUE,
    'visibility_required'                           => ['elements' => ['method', 'property']],
    'whitespace_after_comma_in_array'               => TRUE,
];

$finder = PhpCsFixer\Finder::create()
    ->exclude('vendor')
    ->notPath('src/Symfony/Component/Translation/Tests/fixtures/resources.php')
    ->in(__DIR__);

return PhpCsFixer\Config::create()
    ->setUsingCache(FALSE)
    ->setRules($rules)
    ->setFinder($finder);
